GET http://localhost:3000/users

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "firstName": "Jane",
    "lastName": "Smith",
    "birthday": "2002-01-19",
    "email": "j_smth@gmail.com",
    "city": "New York",
    "username": "j_smth",
    "password": "JJJ"
}

###
GET  http://localhost:3000/users/632f30fe51d53fdaf800b3fe
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMmYzNGFiNTg1ZjBkMjcwYjI1YjgzYyIsImlhdCI6MTY2NDA5NTkxNH0.tqTUX_cILGCSIwFQkjFy7R1JK-yNFqRdkC3kTR17C50

###
PUT http://localhost:3000/users/632f18cd009ba196c3c194c6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMmYxOGNkMDA5YmExOTZjM2MxOTRjNiIsImlhdCI6MTY2NDAzMDkyNn0.19xQIuVJV87wy81Wck1fdtigy_h1Sxl2X9yKhS5U2kM
Content-Type: application/json

{
    "username": "dimabkst",
    "password": "bob"
}

###
DELETE  http://localhost:3000/users/632f15bf1116e5457b816a7d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMmYxNWJmMTExNmU1NDU3YjgxNmE3ZCIsImlhdCI6MTY2NDAzMTA0OH0.XWoQysnYLwEiiijb3UQ5cWIfCtwre7rKJQqpw0SfbNE

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "t_stark@gmail.com",
    "password": "iron"
}

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "firstName": "Tony",
    "lastName": "Stark",
    "birthday": "1980-01-15",
    "city": "New York",
    "password": "iron",
    "email": "t_stark@gmail.com"
}

###
DELETE http://localhost:3000/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMmYzNGFiNTg1ZjBkMjcwYjI1YjgzYyIsImlhdCI6MTY2NDA5NTkxNH0.tqTUX_cILGCSIwFQkjFy7R1JK-yNFqRdkC3kTR17C50