GET http://localhost:3000/users

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "firstName": "Jane",
    "lastName": "Smith",
    "birthday": "2002-01-19",
    "email": "j_smth@gmail.com",
    "city": "New York",
    "username": "j_smth",
    "password": "JJJ"
}

###
GET  http://localhost:3000/users/632f34ab585f0d270b25b83c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMmYzNGFiNTg1ZjBkMjcwYjI1YjgzYyIsImlhdCI6MTY2NDA5NzUxNX0.3W9HW_XMJ3Mx1hWMDr34sF4hXZaG6NEq1xdAse1GMwI

###
PUT http://localhost:3000/users/632f34ab585f0d270b25b83c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMmYzNGFiNTg1ZjBkMjcwYjI1YjgzYyIsImlhdCI6MTY2NDA5NzUxNX0.3W9HW_XMJ3Mx1hWMDr34sF4hXZaG6NEq1xdAse1GMwI
Content-Type: application/json

{
    "username": "ironman",
    "password": "iron"
}

###
DELETE  http://localhost:3000/users/633026a74a150207ade2474d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMzAyNmE3NGExNTAyMDdhZGUyNDc0ZCIsImlhdCI6MTY2NDEwMTcwMH0.v6SVP26Wwnh-BUIpMtrWW_xR0fXQPcnEr0xWr5jTWlU

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "p_parker@gmail.com",
    "password": "web"
}

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "firstName": "Steven",
    "lastName": "Strange",
    "birthday": "1990-01-15",
    "city": "New York",
    "password": "magic",
    "email": "dr_strange@gmail.com"
}

###
DELETE http://localhost:3000/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMmYzNGFiNTg1ZjBkMjcwYjI1YjgzYyIsImlhdCI6MTY2NDA5NzUxNX0.3W9HW_XMJ3Mx1hWMDr34sF4hXZaG6NEq1xdAse1GMwI