POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "t_stark@gmail.com",
    "password": "iron"
}

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "firstName": "Tony",
    "lastName": "Stark",
    "birthday": "1990-01-15",
    "city": "New York",
    "password": "iron",
    "email": "t_stark@gmail.com"
}

###
DELETE http://localhost:3000/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMzQxZTNhYzY3ZTdjYjJjYzY0YWE1YiIsImlhdCI6MTY2NDM2MDAyNX0.YU9X3QkQOF6EaIowmqFD5HGAz92Wk7RllWsKUCF2Dao