POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "t_stark@gmail.com",
    "password": "iron"
}

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "firstName": "Steven",
    "lastName": "Strange",
    "birthday": "1990-01-15",
    "city": "New York",
    "password": "magic",
    "email": "dr_strange@gmail.com"
}

###
DELETE http://localhost:3000/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMmYzNGFiNTg1ZjBkMjcwYjI1YjgzYyIsImlhdCI6MTY2NDA5NzUxNX0.3W9HW_XMJ3Mx1hWMDr34sF4hXZaG6NEq1xdAse1GMwI