GET http://localhost:3000/posts/6334a49e2c3ceab814b5a778/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMzQ5YjUzM2VhY2I5YjcxMjBhNGJlNyIsImlhdCI6MTY2NDM5MjY0OX0.9xxXxFCxeIRjONuFXfhkjRYB_qX8jO4XBmKktPucnG4

###
POST http://localhost:3000/posts/6334a49e2c3ceab814b5a778/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMzQ5YjUzM2VhY2I5YjcxMjBhNGJlNyIsImlhdCI6MTY2NDM5MjY0OX0.9xxXxFCxeIRjONuFXfhkjRYB_qX8jO4XBmKktPucnG4
Content-Type: application/json

{
    "content": "Comment of 2nd best post on this site."
}

###
GET http://localhost:3000/posts/6334a49e2c3ceab814b5a778/comments/6334b3ad07913c9840daaaa9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMzQ5YjUzM2VhY2I5YjcxMjBhNGJlNyIsImlhdCI6MTY2NDM5MjY0OX0.9xxXxFCxeIRjONuFXfhkjRYB_qX8jO4XBmKktPucnG4

###
PUT http://localhost:3000/posts/6334a49e2c3ceab814b5a778/comments/6334b3ad07913c9840daaaa9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMzQ5YjUzM2VhY2I5YjcxMjBhNGJlNyIsImlhdCI6MTY2NDM5MjY0OX0.9xxXxFCxeIRjONuFXfhkjRYB_qX8jO4XBmKktPucnG4
Content-Type: application/json

{
    "content": "Comment of 2nd best post on this site changedd."
}

###
DELETE  http://localhost:3000/posts/6334a49e2c3ceab814b5a778/comments/6334b3ad07913c9840daaaa9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMzQ5YjUzM2VhY2I5YjcxMjBhNGJlNyIsImlhdCI6MTY2NDM5MjY0OX0.9xxXxFCxeIRjONuFXfhkjRYB_qX8jO4XBmKktPucnG4


###
POST  http://localhost:3000/posts/6334a49e2c3ceab814b5a778/comments/6334b3ad07913c9840daaaa9/likes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMzQ5YjUzM2VhY2I5YjcxMjBhNGJlNyIsImlhdCI6MTY2NDM5MjY0OX0.9xxXxFCxeIRjONuFXfhkjRYB_qX8jO4XBmKktPucnG4

###
DELETE  http://localhost:3000/posts/6334a49e2c3ceab814b5a778/comments/6334b3ad07913c9840daaaa9/likes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMzQ5YjUzM2VhY2I5YjcxMjBhNGJlNyIsImlhdCI6MTY2NDM5MjY0OX0.9xxXxFCxeIRjONuFXfhkjRYB_qX8jO4XBmKktPucnG4
