GET http://localhost:3000/searchs/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMzQ1NWE3ZDIwZjNkMDlkOGNkMjkyMyIsImlhdCI6MTY2NDM3NDE4NH0.E3OX0eISAWXQv0efZZDxd_qARS-bsuhceyle8uAWXa4
Content-Type: application/json

{
    "data": "JanE smIth"
}