GET http://localhost:3000/searchs/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMzQ5YjY0M2VhY2I5YjcxMjBhNGJlYSIsImlhdCI6MTY2NDM5MjAzN30.SxFx7DVT9VnZm5fG4x80TTrwe9QBUjPTVD2Vh8C0yXg
Content-Type: application/json

{
    "data": "бобиК"
}