###
GET  http://localhost:3000/users/63349b533eacb9b7120a4be7/friends
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMzQ5YjY0M2VhY2I5YjcxMjBhNGJlYSIsImlhdCI6MTY2NDM5MjAzN30.SxFx7DVT9VnZm5fG4x80TTrwe9QBUjPTVD2Vh8C0yXg

###
DELETE  http://localhost:3000/users/63349b533eacb9b7120a4be7/friends/6334a2312c3ceab814b5a771
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMzQ5YjUzM2VhY2I5YjcxMjBhNGJlNyIsImlhdCI6MTY2NDM5MjY0OX0.9xxXxFCxeIRjONuFXfhkjRYB_qX8jO4XBmKktPucnG4

###
GET  http://localhost:3000/users/6334a2312c3ceab814b5a771/friends/requests/incomings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMzRhMjMxMmMzY2VhYjgxNGI1YTc3MSIsImlhdCI6MTY2NDM5Mzc3N30.7Lvp5AdU4sXG5VGM13rr0T9N8yjkSze9LtQhK2HmStg

###
GET  http://localhost:3000/users/63349b753eacb9b7120a4bed/friends/requests/outcomings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMzQ5YjUzM2VhY2I5YjcxMjBhNGJlNyIsImlhdCI6MTY2NDM5MjY0OX0.9xxXxFCxeIRjONuFXfhkjRYB_qX8jO4XBmKktPucnG4

###
POST  http://localhost:3000/users/63349b753eacb9b7120a4bed/friends/requests/outcomings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMzQ5Yjc1M2VhY2I5YjcxMjBhNGJlZCIsImlhdCI6MTY2NDM5MjA1NH0.s4ITaHrQG3j5l45N8QgFpvbuLDnD283mATnTxL4CTic
Content-Type: application/json

{
    "userId": "63349b643eacb9b7120a4bea"
}

###
GET  http://localhost:3000/users/63349b533eacb9b7120a4be7/friends/requests/outcomings/6334aac62c3ceab814b5a77f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMzQ5YjUzM2VhY2I5YjcxMjBhNGJlNyIsImlhdCI6MTY2NDM5MjY0OX0.9xxXxFCxeIRjONuFXfhkjRYB_qX8jO4XBmKktPucnG4

###
GET  http://localhost:3000/users/6334a2312c3ceab814b5a771/friends/requests/incomings/6334aac62c3ceab814b5a77f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMzRhMjMxMmMzY2VhYjgxNGI1YTc3MSIsImlhdCI6MTY2NDM5Mzc3N30.7Lvp5AdU4sXG5VGM13rr0T9N8yjkSze9LtQhK2HmStg

###
PUT  http://localhost:3000/users/6334a2312c3ceab814b5a771/friends/requests/incomings/6334aee12c3ceab814b5a781
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMzRhMjMxMmMzY2VhYjgxNGI1YTc3MSIsImlhdCI6MTY2NDM5Mzc3N30.7Lvp5AdU4sXG5VGM13rr0T9N8yjkSze9LtQhK2HmStg
Content-Type: application/json

{
    "answer": "Confirm"
}

###
POST  http://localhost:3000/users/6332ad9bce8971bc176efb45/friends/requests/outcomings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMzQ5YjUzM2VhY2I5YjcxMjBhNGJlNyIsImlhdCI6MTY2NDM5MjY0OX0.9xxXxFCxeIRjONuFXfhkjRYB_qX8jO4XBmKktPucnG4
Content-Type: application/json

{
    "userId": "632f34ab585f0d270b25b83c"
}

###
DELETE  http://localhost:3000/users/63349b533eacb9b7120a4be7/friends/requests/outcomings/6334af102c3ceab814b5a782
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMzQ5YjUzM2VhY2I5YjcxMjBhNGJlNyIsImlhdCI6MTY2NDM5MjY0OX0.9xxXxFCxeIRjONuFXfhkjRYB_qX8jO4XBmKktPucnG4

###
GET  http://localhost:3000/users/632f30fe51d53fdaf800b3fe/friends/requests/outcomings/6331d639ac1b7a0ba2686096
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMzQ5YjUzM2VhY2I5YjcxMjBhNGJlNyIsImlhdCI6MTY2NDM5MjY0OX0.9xxXxFCxeIRjONuFXfhkjRYB_qX8jO4XBmKktPucnG4

###
GET  http://localhost:3000/users/632f30fe51d53fdaf800b3fe/friends/requests/incomings/6331d639ac1b7a0ba2686096
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMzQ5YjUzM2VhY2I5YjcxMjBhNGJlNyIsImlhdCI6MTY2NDM5MjY0OX0.9xxXxFCxeIRjONuFXfhkjRYB_qX8jO4XBmKktPucnG4
