GET http://localhost:3000/users

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "firstName": "Jane",
    "lastName": "Smith",
    "birthday": "2002-01-19",
    "email": "j_smth@gmail.com",
    "city": "New York",
    "username": "j_smth",
    "password": "JJJ"
}

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "firstName": "Tony",
    "lastName": "Stark",
    "birthday": "1980-01-19",
    "email": "t_stark@gmail.com",
    "city": "New York",
    "username": "ironman",
    "password": "iron"
}

###
GET  http://localhost:3000/users/63349b533eacb9b7120a4be7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMzQ5YjY0M2VhY2I5YjcxMjBhNGJlYSIsImlhdCI6MTY2NDM5MjAzN30.SxFx7DVT9VnZm5fG4x80TTrwe9QBUjPTVD2Vh8C0yXg

###
PUT http://localhost:3000/users/63349b533eacb9b7120a4be7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMzQ5YjUzM2VhY2I5YjcxMjBhNGJlNyIsImlhdCI6MTY2NDM5MjY0OX0.9xxXxFCxeIRjONuFXfhkjRYB_qX8jO4XBmKktPucnG4
Content-Type: application/json

{
    "password": "iron",
    "phoneNumber": "090990",
    "googleId": "2222"
}

###
DELETE  http://localhost:3000/users/63349b753eacb9b7120a4bed
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMzQ5Yjc1M2VhY2I5YjcxMjBhNGJlZCIsImlhdCI6MTY2NDM5MjA1NH0.s4ITaHrQG3j5l45N8QgFpvbuLDnD283mATnTxL4CTic
