GET http://localhost:3000/users

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "firstName": "Jane",
    "lastName": "Smith",
    "birthday": "2002-01-19",
    "email": "j_smth@gmail.com",
    "city": "New York",
    "username": "j_smth",
    "password": "JJJ"
}

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "firstName": "Tony",
    "lastName": "Stark",
    "birthday": "1980-01-19",
    "email": "t_stark@gmail.com",
    "city": "New York",
    "username": "ironman",
    "password": "iron"
}

###
GET  http://localhost:3000/users/6332ee34d4a599102aea9761
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMzJlZTM0ZDRhNTk5MTAyYWVhOTc2MSIsImlhdCI6MTY2NDI4MjIxMX0.VG_v2J3QmU8rZBJGPE96bpCRbU9tkGqAs8EhucWHLjk

###
PUT http://localhost:3000/users/6332ee34d4a599102aea9761
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMzJlZTM0ZDRhNTk5MTAyYWVhOTc2MSIsImlhdCI6MTY2NDI4MjIxMX0.VG_v2J3QmU8rZBJGPE96bpCRbU9tkGqAs8EhucWHLjk
Content-Type: application/json

{
    "password": "iron"
}

###
DELETE  http://localhost:3000/users/63341e3ac67e7cb2cc64aa5b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMzQxZTNhYzY3ZTdjYjJjYzY0YWE1YiIsImlhdCI6MTY2NDM2MDIwNH0.EvydaO_8Zx6_YEGLPVZoYx6IFvTesFPVL3e4MtSQ99Q
